# Generated by Django 4.0.6 on 2022-07-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_category',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
