# Generated by Django 4.0.6 on 2022-07-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=50)),
                ('subject', models.TextField(max_length=100)),
                ('message', models.TextField(max_length=225)),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
